### ISSUE TITLE
"Run BUSCO" page

### ISSUE THREAD

**Issue by onabluemoon** [ezlab/odb_gui#104]
A page for submitting BUSCO runs.
Should be a simpler version of the "Own Data & Mapping", with the following changes:
1- The  "Run Analysis" post request should also included the argument: "anatype" = "busco" 
2-  Fields on the middle part (where the user inputs "Species name" and selects "Map To" and "Place At"), should changed. The fields should be: "File name" (exactly like it is implemented already), "Run Name" (free text, same as "Species name") and "BUSCO clade" (drop-down menu with fixed contents).
3- The results table fields should be named: "File name", "Run Name", "BUSCO clade", "Complete (single-copy)", "Complete (multi-copy)", "Fragmented",  "Missing", "Total"

**Comment by kamushkin** [comment]
I have added the option to choose analysis type to the existing page -

![image](https://cloud.githubusercontent.com/assets/9464404/20837895/6e9ae2c2-b8a6-11e6-9676-bf0bf4bbd4cc.png)

see https://github.com/ezlab/odb_gui/commit/e80ed8dca68b95332e7a7d378ad7715b3955b1d0

**Comment by onabluemoon** [comment]
Perfect
