### ISSUE TITLE
add after "Orthologs by organism": ["all species" | "only example species" | "only selected species"]

### ISSUE THREAD

**Issue by zdevg** [ezlab/odb_gui#63]
- actually, we need a selector among the options below as you have now for all/selected.

if !species : "only example species" 
elsif: species == level : "all XX species" 
else : "only selected species"

- XX number comes from "genes in XX species" in Phyletic Profile

![screen shot 2015-02-09 at 12 47 07 pm](https://cloud.githubusercontent.com/assets/9463660/6105645/cb55d67c-b059-11e4-97cd-f79c6ff29b98.png)

**Comment by kamushkin** [comment]
not necessary, see #71
