### ISSUE TITLE
allow a tree node selection without any leaf selection

### ISSUE THREAD

**Issue by zdevg** [ezlab/odb_gui#71]
We have 2 parameters defined from the tree: level & species(node ids are allowed in the list),
the backend is now interpret the species=null as 'examples' only from this level,
yet current gui does not allow to leave species as null (removes level selection if everything is unchecked)

**Comment by kamushkin** [comment]
![image](https://cloud.githubusercontent.com/assets/9464404/6348936/208b9d76-bc25-11e4-808e-08109304c013.png)

done
