### ISSUE TITLE
Files request should return 401 (Non authorized) for non-authenticated users

### ISSUE THREAD

**Issue by kamushkin** [ezlab/odb_gui#82]
At the moment the request is redirected to the login page which makes no sense for API calls. The request should return 401 instead, and the login page will be called by the UI code.

**Comment by ftegenfe** [comment]
I modified the backend a bit. Doing http://ezmeta.unige.ch/odb/dev/files unauthenticated will return the json
{"status": "error", "message": "user not authenticated", "data": []}

Was that the issue?

**Comment by kamushkin** [comment]
Status 401 is better because we do not show an error to the user - just redirect to the login screen.
