### ISSUE TITLE
Login button not displaying properly

### ISSUE THREAD

**Issue by onabluemoon** [ezlab/odb_gui#84]
It seems one of the last updates introduced a bug n with the "login / logout" button on the main page.
The button is only showing up as "logout", even when the user is not currently logged in.

**Comment by kamushkin** [comment]
This happens because /user handler returns an array in the data attribute, while I am expecting it to be null/undefined. 
```
{"status": "ok", "message": null, "data": []}
```
Could you remove data attribute or change it to null ?

https://github.com/ezlab/odb_gui/wiki/User-request
