### ISSUE TITLE
login pop-up

### ISSUE THREAD

**Issue by zdevg** [ezlab/odb_gui#96]
re problem with blank login popup:
it seems it gets blocked when accessed when redirected from http://www.orthodb.org/v9.1/
and works from http://ezmeta.unige.ch/odb/dev/

more over, i have logged in status on ezmeta.unige.ch and not logged in on orthodb.org/v9.1/
but m.b. it is an effect of having them in 'incognito' mode though both as tabs in the same window.

**Comment by kamushkin** [comment]
The issue is with login handler ( http://www.orthodb.org/v9.1/login ) returning error instead of redirecting to the login form
```
{"status":400,"code":2002,"message":"jwtBody cb_uri is an invalid value.","developerMessage":"jwtBody cb_uri is an invalid value.","moreInfo":"https://docs.stormpath.com/rest/product-guide/latest/errors.html#error-2002","requestId":"b0425f50-86f8-11e6-bc66-22000b248dca"}
```
Possibly because callback URI on the live site is not registered in stormpath control panel
